### ISSUE TITLE
compiling LESS via theme

### ISSUE THREAD

**Issue by gegere** [bassjobsen/jbst#115]
Hello, Can you help point me in the correct direction for compiling LESS to output the wpless2css.css file?

**Comment by bassjobsen** [comment]
Hi @gegere 

Thanks for you question. I'm happy to help you.

Also see (step 4): https://github.com/bassjobsen/jamedo-bootstrap-start-theme/issues/86#issuecomment-33525619

The most important step in compiling a new version of wpless2css.css is run the compiler.

Appearance > Compiler and press the "Recompile LESS code":

![recompile](https://f.cloud.github.com/assets/954055/2343727/a95a6170-a513-11e3-8b9c-ce5d1e4fe09d.png)

You can add your custom LESS code into the editor direct or add it to:  library/assets/less/custom.less (less/custom.less for child themes) or wpless2css/wpless2css.less (backup when updating the theme!).

Hope this helps? Otherwise please let me know.
