### ISSUE TITLE
Child themes not working

### ISSUE THREAD

**Issue by nofake** [bassjobsen/jbst#83]
Hi,
i´m trying your theme and the child theme boilerplate and the ecommerce one and they do not work, in wordpressthey tell me imposible to find paren theme , jamedo-bootstrap start theme, can you help ? i have no idea why is not working
best,
:)

**Comment by bassjobsen** [comment]
Hi,

Thanks for posting your issue. Of course i can help you.
What is the directory of the parent theme? When unzipping it will add -master, so you will have `jamedo-bootstrap-start-theme-master` instead of `jamedo-bootstrap-start-theme`.

the child theme needs the correct path. The path is set in themes/Boilerplate-JBST-Child-Theme{-master}/style.css: `@import url(../jamedo-bootstrap-start-theme/style.css);`. 

To fix you will have to change the folder of the master theme (JBST) or the path in style.css of the child theme.

Hope this helps? Please let me know.

**Comment by nofake** [comment]
it works thanks

**Comment by bassjobsen** [comment]
yw! please let us know when you child theme has been finished to we could add it to http://expo.jbst.eu/
