### ISSUE TITLE
Full width

### ISSUE THREAD

**Issue by ghost** [bassjobsen/jbst#95]
Feature request : It would be great to enable a "Full width" option to the grid.
Can I accomplish that with editing LESS files ?

**Comment by bassjobsen** [comment]
Hi @linearis,

Thanks for your question.
In the LESS editor add `.container{width:100%;}` and recompile your LESS.

You can also add this line to less/custom.less (and recompile).

Regards,

Bass

**Comment by ghost** [comment]
Will this be overrided by theme updates ?

2014-01-27 Bass Jobsen notifications@github.com

**Comment by bassjobsen** [comment]
Nope. The code you edit in the LESS editor / compiler is saved in the database and won't be overwritten.
less/custom.less should be in your child theme directory and so isn't overwritten too.

NOTE if you edit your changes in the parent theme  (/library/assets/less/custom.less) are overwritten with an update!

**Comment by ghost** [comment]
Ok it works ! I used the LESS editor. Will you plan this option in customizer  in further versions ?

**Comment by bassjobsen** [comment]
Well i plan it now :)
I will add it to the "container width" options.
Also consider to extend the grids: http://stackoverflow.com/questions/21351139/responsive-design-on-which-component-should-be-responsive/21364956

**Comment by bassjobsen** [comment]
In the current version you can choose full (fluid) for your container width in the customizer.
This sets the width based on Bootstrap's (reintroduced) container-fluid class (since v 3.1.0), see also: http://getbootstrap.com/css/#grid-options.

Note this setting only sets the content container. Navbar already full width option. The footer also got a full width option before. Although closing this issue now, the footer and navbar / header don't always as expect now. The footer only sets a 100% background when choosing full width for example.
